[env:attiny45]
platform = atmelavr
board = attiny45
framework = arduino
board_build.f_cpu = 8000000L

; To upload using the Ladyada USBtinyISP, uncomment the following:
upload_protocol = usbtiny

; To upload using an Arduino as ISP, uncomment the following:
; upload_protocol = custom
; upload_port = /dev/ttyACM0
; upload_speed = 19200
; upload_flags =
;     -C
;     $PROJECT_PACKAGES_DIR/tool-avrdude/avrdude.conf
;     -p
;     $BOARD_MCU
;     -P
;     $UPLOAD_PORT
;     -b
;     $UPLOAD_SPEED
;     -c
;     stk500v1
; upload_command = avrdude $UPLOAD_FLAGS -U flash:w:$SOURCE:i

; To upload using the CJMCU / Digispark USB board, uncomment:
; upload_protocol = micronucleus

lib_deps =
    z3t0/IRremote @ ^4.2.0
